### ISSUE TITLE
Consider implementing part of that as a reusable library

### ISSUE THREAD

**Issue by fabricedesre** [little-bear-labs/ipfs-chromium#2]
Hi,

I think it would be valuable to implement the chromium support in 2 components:

1. A  `libipfsclient` library that deals with IPFS specific bits, and exposes hooks to the host using the library. That would likely cover:
- Low level CID / multihash bits.
- The UnixFS state machine to decode and verify blocks (DAG, HAMT).
- The block store.
- IPNS resolution.
2. The chromium glue code.

The host (here chromium) would provide http networking, low level DNS, heuristic for gateway scoring, etc.

This would make it possible to share the IPFS specific bits among web runtimes (and other targets) more easily. I would be interested to re-use that for a Gecko and Servo implementations for instance.

**Comment by John-LittleBearLabs** [comment]
Agreed that code sharing would be desirable if it works out. Organizing in 2 components rather than 1 seems pretty low-cost from my end, so definitely will take this into consideration.
