### ISSUE TITLE
Support gateway override via `IPFS_GATEWAY`  ENV

### ISSUE THREAD

**Issue by lidel** [little-bear-labs/ipfs-chromium#29]
Current list of [trustless gateways](https://specs.ipfs.tech/http-gateways/trustless-gateway/) is hardcoded in 

https://github.com/little-bear-labs/ipfs-chromium/blob/0e8d229d7898f7d2bc032ab9cc14d60dfd7c369b/library/src/ipfs_client/gateways.cc#L68-L89

To make it easier to test against own gateway running on a different port, or dofferent public ones, we could check if `IPFS_GATEWAY` is present in ENV, and if so, use its value as whitespace-separated list of gateways to use instead of the  hardcoded one.

**Comment by lidel** [comment]
Yes, it is based on https://github.com/ipfs/kubo/issues/8847 and https://github.com/curl/curl/pull/8805, went with `IPFS_GATEWAY` as most of the time user will set this to their preferred (local/LAN) gateway, so when set, plural option will rarely be used.

**Comment by John-LittleBearLabs** [comment]
Merged into main under unrelated PR (sorry)
