### ISSUE TITLE
Server-Timing 'ipns record request' for  DNSLink is bogus

### ISSUE THREAD

**Issue by lidel** [little-bear-labs/ipfs-chromium#40]
If I open DNSLink website, i use no IPNS record lookup, but there is still the server-timing header:

Example: open ipns://en.wikipedia-on-ipfs.org/wiki/World_War_II and see:
```
Server-Timing:
ipns;desc="IPNS record request";dur=-6148914691236517206
```

@John-LittleBearLabs  i think the fix is to not set the value for DNSLink.

**Comment by John-LittleBearLabs** [comment]
I know this issue is ancient, and the implementation hasn't changed recently, but I suspect somewhere along the line it got fixed as this is now what I see:

![image](https://github.com/user-attachments/assets/dadbf33b-99f0-4805-b5ff-172acdd1391a)
