### ISSUE TITLE
macOS builds

### ISSUE THREAD

**Issue by BigLep** [little-bear-labs/ipfs-chromium#43]
@John-LittleBearLabs : will there be builds for macOS?  I didn't see anything listed in https://github.com/little-bear-labs/ipfs-chromium/releases/tag/0.0.0.3 .  I see there is for https://github.com/little-bear-labs/ipfs-chromium/releases/tag/0.0.0.2

**Comment by John-LittleBearLabs** [comment]
The short answer is yes, there will be.
I'm working on getting a functioning signing identity & process set up again on the new mac box. Currently on the last roadblock I recall from the last time, on which I apparently took too few notes.

**Comment by John-LittleBearLabs** [comment]
ipfs-chromium-mac.zip uploaded. Sorry for the delay.
