### ISSUE TITLE
dnslink doesn't work with macOS 0.0.0.3 build

### ISSUE THREAD

**Issue by sukunrt** [little-bear-labs/ipfs-chromium#44]
ipns://en.wikipedia-on-ipfs.org/ doesn't work on macOS.

**Comment by John-LittleBearLabs** [comment]
Hmm. It worked for me just now. Is it possible you caught it in the middle of a DNS update or something quirky like that?
![image](https://github.com/little-bear-labs/ipfs-chromium/assets/97759690/9e908616-2d5a-4244-803c-7573a6060ce5)

**Comment by lidel** [comment]
@sukunrt  #43 got merged, mind checking if https://github.com/little-bear-labs/ipfs-chromium/releases/download/0.0.0.3/ipfs-chromium-mac.zip works for you?

**Comment by sukunrt** [comment]
Sorry I missed the previous message. 
This is still not working. How can I help debug this?

**Comment by John-LittleBearLabs** [comment]
> Sorry I missed the previous message. This is still not working. How can I help debug this?

Sorry to hear that. 

You could try checking/uploading logs. 
https://support.google.com/chrome/a/answer/6271282?hl=en#zippy=%2Cmac
I would think you _probably_ don't need to go to verbose logging (you may omit the `--v=1`)

Next time I have a Mac plugged in I'll give it a shot myself, and if it's still working for me I'll do a recording (not just a screenshot) so you can check and see if I'm doing something differently.

**Comment by sukunrt** [comment]
Thanks for pointing me to logging. That did help me resolve the issue. 

Turns out I have some misconfiguration with tailscale DNS. Maybe it is picking up the tailscale name server(100.100.100.100). But it works after I disable tailscale. It also works if I explicitly set the dns server in chromium to 1.1.1.1.
