### ISSUE TITLE
Build & Feature flags

### ISSUE THREAD

**Issue by John-LittleBearLabs** [little-bear-labs/ipfs-chromium#50]
From milestone 2.b: 
> Develop compile- and run-time switches for enabling/disabling the IPFS integration.

**Comment by E-investment217** [comment]
| Header |
|--------|
| Cell | data/user/0/com.termoneplus/app_HOME

**Comment by E-investment217** [comment]
Cool

**Comment by John-LittleBearLabs** [comment]
> Cool

@E-investment217 - I'm guessing you're referring to Github's rendering of tables in Markdown?
