### ISSUE TITLE
2b7b03f8e062b1d54a50cf6406170acab01b2c69

### ISSUE THREAD

**Issue by E-investment217** [little-bear-labs/ipfs-chromium#76]
https://github.com/airbnb/lottie-android/commit/2b7b03f8e062b1d54a50cf6406170acab01b2c69

**Comment by John-LittleBearLabs** [comment]
Would you mind clarifying (in English prose) what it is you'd like to see happen?

**Comment by John-LittleBearLabs** [comment]
In the future, please explain your issues, otherwise I have to assume they're spam.
