### ISSUE TITLE
Daily requests of App Engine Admin API

### ISSUE THREAD

**Issue by E-investment217** [little-bear-labs/ipfs-chromium#78]
![chart_API_DAILY_REQUESTS4365902032941336509.png](https://github.com/little-bear-labs/ipfs-chromium/assets/145872352/0a06ab7d-cd05-49a6-92b7-0e9ca9d6b06b)

**Comment by John-LittleBearLabs** [comment]
I don't know what app you even have in mind. No one has been providing daily requests.
