### ISSUE TITLE
Question about your licence model

### ISSUE THREAD

**Issue by uazo** [little-bear-labs/ipfs-chromium#88]
currently in your repo I have not found the type of licence of your project.
is it possible to know which licence you will be using?
thank you for your reply

**Comment by John-LittleBearLabs** [comment]
3 weeks! My gosh, I'm sorry I didn't see this sooner.

That's an excellent question. From my perspective, it's whatever the client wants. I'll ask in our meeting tomorrow.

Since we'd like to land code in Chromium eventually, certainly we'll choose a license acceptable to that project.

**Comment by John-LittleBearLabs** [comment]
@uazo - do you have a strong preference? I can pass along your input.

**Comment by uazo** [comment]
> 3 weeks! My gosh, I'm sorry I didn't see this sooner.

don't worry, no problem.

> Since we'd like to land code in Chromium eventually, certainly we'll choose a license acceptable to that project.

is what I thought, but I was looking for confirmation.
If it's acceptable for chromium, that's fine with me too.

> do you have a strong preference? I can pass along your input

no, none of course, at least now!
My question was for the purpose of understanding whether it was not worth it to check your code because of the incompatible license with my project.

**Comment by John-LittleBearLabs** [comment]
So yes, we're willing to go with a Chromium license. This article is also very applicable:

https://protocol.ai/blog/announcing-the-permissive-license-stack/

So we may be willing to dual- or triple-license.

I'm going to leave this issue open until we get a LICENSE file in the repo.
